export const initialState = {
  Sex: "",
  Age: "",
  Education: "",
  Income: "",
  BMI: "",
  HighBP: "",
  HighChol: "",
  CholCheck: "",
  Stroke: "",
  Diabetes: "",
  DiffWalk: "",
  Smoker: "",
  PhysActivity: "",
  Fruits: "",
  Veggies: "",
  HvyAlcoholConsump: "",
  GenHlth: "",
  MentHlth: 0,
  PhysHlth: 0,
  AnyHealthcare: "",
  NoDocbcCost: "",
};

export const labels = {
  Sex: "Sex",
  Age: "Age range",
  Education: "Highest education completed",
  Income: "Annual household income",
  BMI: "Body mass index (BMI)",
  HighBP: "High blood pressure",
  HighChol: "High cholesterol",
  CholCheck: "Cholesterol checked in last 5 years",
  Stroke: "History of stroke",
  Diabetes: "Diabetes status",
  DiffWalk: "Difficulty walking or climbing stairs",
  Smoker: "Smoked 100+ cigarettes in your life",
  PhysActivity: "Physical activity in the last 30 days",
  Fruits: "Eats fruit at least once a day",
  Veggies: "Eats vegetables at least once a day",
  HvyAlcoholConsump: "Heavy alcohol consumption",
  GenHlth: "Self-rated general health",
  MentHlth: "Poor mental health days (last 30)",
  PhysHlth: "Poor physical health days (last 30)",
  AnyHealthcare: "Has healthcare coverage",
  NoDocbcCost: "Skipped care due to cost (last 12 months)",
};

export const tooltips = {
  Sex: "Biological sex as recorded in the underlying health survey.",
  Age: "Your age band. The model was trained on 5-year age bands rather than exact age.",
  Education: "The highest level of school you have completed.",
  Income: "Your total household income before taxes, for the past year.",
  BMI: "Weight (kg) divided by height in meters, squared. Use the calculator below if you only know height and weight.",
  HighBP: "Has a doctor, nurse, or health professional ever told you that you have high blood pressure?",
  HighChol: "Has a doctor, nurse, or health professional ever told you that your cholesterol is high?",
  CholCheck: "Have you had your cholesterol checked in the past 5 years?",
  Stroke: "Has a doctor, nurse, or health professional ever told you that you had a stroke?",
  Diabetes: "Includes prediabetes/borderline diabetes as a separate answer from a confirmed diagnosis.",
  DiffWalk: "Do you have serious difficulty walking or climbing stairs?",
  Smoker: "Have you smoked at least 100 cigarettes (about 5 packs) in your entire life?",
  PhysActivity: "Any physical activity or exercise in the past 30 days, other than your regular job.",
  Fruits: "On average, do you eat one or more servings of fruit per day?",
  Veggies: "On average, do you eat one or more servings of vegetables per day?",
  HvyAlcoholConsump: "Adult men having more than 14 drinks per week, or adult women more than 7 drinks per week.",
  GenHlth: "In general, how would you rate your overall health?",
  MentHlth: "Thinking about your mental health, including stress, depression, and emotional problems, for how many days in the past 30 was it not good?",
  PhysHlth: "Thinking about your physical health, including illness and injury, for how many days in the past 30 was it not good?",
  AnyHealthcare: "Do you currently have any kind of health insurance or coverage plan?",
  NoDocbcCost: "In the past 12 months, was there a time you needed to see a doctor but couldn't because of cost?",
};

export const yesNo = [
  { label: "No", value: 0 },
  { label: "Yes", value: 1 },
];

export const options = {
  Sex: [
    { label: "Female", value: 0 },
    { label: "Male", value: 1 },
  ],
  Age: [
    { label: "18–24", value: 1 },
    { label: "25–29", value: 2 },
    { label: "30–34", value: 3 },
    { label: "35–39", value: 4 },
    { label: "40–44", value: 5 },
    { label: "45–49", value: 6 },
    { label: "50–54", value: 7 },
    { label: "55–59", value: 8 },
    { label: "60–64", value: 9 },
    { label: "65–69", value: 10 },
    { label: "70–74", value: 11 },
    { label: "75–79", value: 12 },
    { label: "80 or older", value: 13 },
  ],
  Education: [
    { label: "Never attended school", value: 1 },
    { label: "Grades 1–8 (Elementary)", value: 2 },
    { label: "Grades 9–11 (Some high school)", value: 3 },
    { label: "High school graduate or GED", value: 4 },
    { label: "Some college or technical school", value: 5 },
    { label: "College graduate", value: 6 },
  ],
  Income: [
    { label: "Under $10,000", value: 1 },
    { label: "$10,000–$14,999", value: 2 },
    { label: "$15,000–$19,999", value: 3 },
    { label: "$20,000–$24,999", value: 4 },
    { label: "$25,000–$34,999", value: 5 },
    { label: "$35,000–$49,999", value: 6 },
    { label: "$50,000–$74,999", value: 7 },
    { label: "$75,000 or more", value: 8 },
  ],
  GenHlth: [
    { label: "Excellent", value: 1 },
    { label: "Very good", value: 2 },
    { label: "Good", value: 3 },
    { label: "Fair", value: 4 },
    { label: "Poor", value: 5 },
  ],
  Diabetes: [
    { label: "No", value: 0 },
    { label: "Prediabetes / borderline", value: 1 },
    { label: "Yes, diagnosed diabetes", value: 2 },
  ],
  HighBP: yesNo,
  HighChol: yesNo,
  CholCheck: yesNo,
  Stroke: yesNo,
  DiffWalk: yesNo,
  Smoker: yesNo,
  PhysActivity: yesNo,
  Fruits: yesNo,
  Veggies: yesNo,
  HvyAlcoholConsump: yesNo,
  AnyHealthcare: yesNo,
  NoDocbcCost: yesNo,
};

export const steps = [
  {
    id: "about-you",
    title: "About You",
    description: "Demographic basics used to contextualize your result.",
    fields: ["Sex", "Age", "Education", "Income", "BMI"],
  },
  {
    id: "health-history",
    title: "Health History",
    description: "Conditions you've been diagnosed with or screened for.",
    fields: ["HighBP", "HighChol", "CholCheck", "Stroke", "Diabetes", "DiffWalk"],
  },
  {
    id: "lifestyle",
    title: "Lifestyle & Habits",
    description: "Day-to-day habits that shape long-term cardiovascular risk.",
    fields: ["Smoker", "PhysActivity", "Fruits", "Veggies", "HvyAlcoholConsump"],
  },
  {
    id: "wellbeing",
    title: "Wellbeing & Access to Care",
    description: "How you've felt recently, and whether care has been reachable.",
    fields: ["GenHlth", "MentHlth", "PhysHlth", "AnyHealthcare", "NoDocbcCost"],
  },
];
